### ISSUE TITLE
not working on macOS 14.3.1 Sonoma

### ISSUE THREAD

**Issue by Lenaku917** [jasonjmcghee/plock#26]
I tried building it and also directly download the dmg version. The menu bar icon is there. I enabled input monitoring in the settings app. I changed the settings.json file (see attachment). I tried 'load settings' and quitting it. But when I select the prompt and press the shortcut, it doesn't seem to be doing anything. And yes I do have ollama and the dolphin-mistral module. Directly running the module with ollama works fine. I've tried restarting my mac, but nothing seems to work. I would appreciate to know if the settings.json file is set up correctly and is hopefully just a user error.
My Terminal is in zsh, I’m not sure if that effects it.
<img width="549" alt="dolphin-mistrsal running" src="https://github.com/jasonjmcghee/plock/assets/109910644/c916bfd3-03a8-4281-999c-56b2595c4e44">
<img width="463" alt="settingsJson" src="https://github.com/jasonjmcghee/plock/assets/109910644/5ee26895-bc8b-43c3-ba6b-a1071347a325">

**Comment by jasonjmcghee** [comment]
Big apologies, missed this issue.

I use zsh myself, but this bypasses whatever you might use in your terminal and uses bash directly.

Can you try running the binary directly from the terminal? That should output logs, and you can see if there's an error.

Otherwise, you can try manually turning on "Accessibility" (and "Input Monitoring").

I'd also try removing plock from both "Accessibility" and "Input Monitoring" and re-launching.

Hoping you find success 🤞 but I don't have a clear path to success here.

Really need better logging...

**Comment by Lenaku917** [comment]
Running the binary directly from terminal gives a warning that 'Secure coding is not enabled for restorable state...' 
Other than this warning, there are no errors and the app works totally fine! Which led me to think that theres something wrong with the accessibility. And yes, the app asks for "Input Monitoring" access but somehow **never asked for the "Accessibility"** 🤷. **Manually adding plock to "Accessibility" did the trick!** Thanks for the help! 😁
